---
- hosts: all
  remote_user: ansible
  gather_facts: false
  vars:
    version: 1.16.1

  tasks:
    - name: update docker
      apt:
        update_cache: yes
        name: docker-ce
        only_upgrade: yes

    - name: update docker-compose
      shell: "sudo curl -L https://github.com/docker/compose/releases/download/{{ version }}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose"